services:
  tika:
    image: docker.io/apache/tika:latest
    container_name: tika
    restart: unless-stopped
    env_file:
      - ../../../.env
      - .env
    networks:
      paperless-stack:
        aliases:
          - tika

networks:
  paperless-stack:
    external: true
